version: '2'
services:
    eazykar-app:
        image: eazykar
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://142.93.206.254:3306/eazykar?useUnicode=true&characterEncoding=utf8&useSSL=false
            - EZKR_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    #eazykar-mysql:
        #extends:
            #file: mysql.yml
            #service: eazykar-mysql
