version: '2'
services:
    eazykar-mysql:
        image: mysql:8
        environment:
            - MYSQL_USER=ezkr_dbuser
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_DATABASE=eazykar
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
        restart: always
